services:
  backend:
    build: ./server
    container_name: krist-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: always
    networks:
      - krist-network

  frontend:
    build: ./client
    container_name: krist-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - krist-network

networks:
  krist-network:
    driver: bridge